name: Generate tables on BigQuery

on:
  release:
    types: [published]
    branches: ["main"]

jobs:
  create-tables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run make_concepts
        run: |
            echo "Generating tables on BigQuery"
            cd mimic-iv/concepts
            bash make_concepts.sh